### ISSUE TITLE
gdxxrw command error

### ISSUE THREAD

**Issue by gunthecl** [chrispahm/linter-gams#16]
Ive properly installed linter gams and all dependent packages. Everytime I try to run my model (which works fine in GAMS 24.7.) I get the error messages "sh: gdxxrw: command not found
Resaving the file usually solves this error."

**Comment by chrispahm** [comment]
Hey there,
could you tell me a little bit more about your setup?
If you are working on MacOS/Linux, then GDXXRW is not available for your system (GAMS has a [compatibility chart here](https://www.gams.com/latest/docs/T_MAIN.html#GAMS_TOOLS_SUPPORTED_PLATFORMS) for all their tools). 
On Windows however, I just checked a model using GDXXRW and it was working alright for me. If you are on Windows as well, it could be helpful if you could post your model here!

**Comment by chrispahm** [comment]
I guess you have (at least) these two options:

a) If your data changes frequently and you would like to keep it in a spreadsheet, then I guess switching from an Excel format (.xls or .xlsx) to .csv would be a good option. You can still edit the .csv with Excel or any other spreadsheet program as OpenOffice, Google Docs, Numbers etc. The .csv import is explained in the [GAMS documentation](https://www.gams.com/latest/docs/T_CSV2GDX.html). Another advantage of this approach is that the model will be platform independant.

b) If the data for the model never (or rarely) changes AND you have access to a Windows machine that runs GAMS, you could convert the desired data from the Excel sheet into a .gdx file there. Instead of calling GDXXRW then, you could just import the .gdx file (which will also work on all platforms).
You can find out more on how to create the .gdx output file in the [GDXXRW documentation](https://www.gams.com/latest/docs/T_GDXXRW.html).

In any case, my experience is that GDXXRW slows down the compile time significantly (in most cases), which is why I try to avoid it as much as possible. You will find some reference on how to improve it [here](https://support.gams.com/interfaces:gdxxrw_is_slow) or [here].

**Comment by gunthecl** [comment]
Thank you some much for your valuable comments! Ive spent quite some time already trying to get the model run on OS X and had a hard time to understand all the obstacles.

I will try to implement both options and see with one is more suitable for the model at hand. Thanks again - your explanation was very valuable for me!

**Comment by chrispahm** [comment]
No worries, glad to help 😊
