### ISSUE TITLE
Error handling - redirecting to line

### ISSUE THREAD

**Issue by samarthiith** [chrispahm/linter-gams#32]
Hi!
Love the package. A feature I would love to have is being able to be directed to error line from .lst file.
Are there plans to include something this?
Best,
Samarth

**Comment by chrispahm** [comment]
Hi Samarth,

thanks for the love ❤️!
As you know, when you `save` your file, the GAMS model is checked for compilation errors in the background (the green dot in the statusbar turns orange and blinks during the checking), and the error is displayed like this:
![Kapture 2019-06-07 at 10 01 23](https://user-images.githubusercontent.com/20703207/59089856-6e51a200-890b-11e9-8bbd-f6363c061977.gif)

Now I guess what you are interested in, is having a toolbar that can be clicked that will jump to the next error (even when it's in a different GAMS file than the one currently opened).
![Kapture 2019-06-07 at 10 06 17](https://user-images.githubusercontent.com/20703207/59090149-3bf47480-890c-11e9-92e4-82e87e6deae5.gif)

You can achieve this by activating the following settings in the `linter-ui-default` package:

![image](https://user-images.githubusercontent.com/20703207/59090188-60505100-890c-11e9-9700-f16b8a0cbf63.png)
![image](https://user-images.githubusercontent.com/20703207/59090199-67775f00-890c-11e9-9bf1-1ec0689f021c.png)

Is that what you are looking for?
Best,
Christoph

**Comment by samarthiith** [comment]
This is a great way to handle error but unfortunately, it doesn't work for me. The background check stops when it finds the first error (which makes sense for performance issues). The problem is my code extends through multiple files so for example parameter used is declared in an upper-level file but is recognized as an error in the current file and it stops checking for further errors. 
Does that make sense?
Any suggestion on how to handle this?

**Comment by chrispahm** [comment]
Alright, so if I understand you correctly, you have a top level Gams file that you are executing when you want to run your model? If that is the case (which is common for larger models), you want to specify the multi-file-entry point in the settings of the linter-gams package. That way, when you are in a different file, and save it, the correct errors are shown (which I think is what you want to achieve). I’m currently not on my PC and can’t show you an example, but there is a section about this in the read me file.

**Comment by chrispahm** [comment]
So I wanted to follow up with another example for this:
If you look at the [model for our crop rotation application (Fruchtfolge)](https://github.com/fruchtfolge/model),
you can see that there is the following model structure:
```
debug.gms
  test/include/farm1.gms
  fruchtfolge.gms
    model/labour.gms
    ...
```
so, our debug.gms file is the top level file that needs to be called when the model should be run locally in GAMS (as the name suggests, in order to debug the model). Ideally, we would not only call this file when we run the model, but let `linter-gams` know, that when we are any other file in the model it just starts the compilation check with `debug.gms`, and not the file that we are currently looking at. In order for this to work, there are two options: 
- either, one adds `debug.gms` to the Multi-File-Entry point setction in the `linter-gams` settings
![image](https://user-images.githubusercontent.com/20703207/59142514-cba72b00-89bf-11e9-9922-5e3a525fe225.png)
- or one creates a `.gamslintc.js` file in the model root directory (recommended). This file stores project specific settings for `linter-gams`, making it easier to work with multiple models. You can check out the [one of the Fruchtfolge model here](https://github.com/fruchtfolge/model/blob/master/.gamslintc.js)

Now the last thing to make sure is that the models root directory is added as the project directory in Atom (otherwise it can't find the entry point)
![image](https://user-images.githubusercontent.com/20703207/59142579-c7c7d880-89c0-11e9-9fae-8f9f74820637.png)

Now if everything is set-up correctly, you can hit save in any file and it should direct you to the "correct" errors, also you can now start the model from any file, and don't have to navigate to the entry point file first.

Best
Christoph

**Comment by samarthiith** [comment]
Thanks a lot, it works now!
Much appreciate your effort. :)

Best,
Samarth
